"""Fast-ice backscatter from Sentinel-1 C-band SAR.

Why SAR and not optical
-----------------------
During the austral polar night the sun does not rise for months. Optical
imagery is useless, and passive microwave cannot resolve the metre-to-hundred-
metre fracture structure that determines whether a colony's fast ice will hold.
C-band SAR penetrates nothing but is indifferent to the sun: it measures the
*surface* dielectric and roughness, which is exactly what fast ice, nilas, leads
and open water differ by.

The physics the model encodes
-----------------------------
Calibrated sigma0 for the four surface states that matter, from the
Antarctic SAR literature:

==========================  ==========================  ===================
State                       sigma0 HH (dB)             Cause
==========================  ==========================  ===================
Consolidated first-year     -8 to -3                    brine channels and
                            (brighter)                  wind-roughened surface
Rough, ridged ice           -6 to -1                    pressure ridges and
                                                         rafted floes
Thin nilas / new ice        -13 to -9                   low roughness, no
                                                         volume scattering
Open water / lead           -20 to -12                  specular reflection
                                                         away from sensor
==========================  ==========================  ===================

The operational consequence: a *drop* in mean sigma0 between acquisitions
is the standard remote-sensing signature of a lead opening, and a drop in the
*frozen* fraction is the signature of the fast-ice tongue detaching from the
coast. That is what :meth:`~emperor_space_tracker.models.SarScene.classify`
grades, and what the alerting rules key off.

Two backends
------------
``gee``
    Genuine retrieval. Requires ``earthengine-api`` and a completed
    ``earthengine authenticate``. The reduction is a per-scene ``reduceRegion``
    over a colony-centred buffer, so the client only ever pulls a few hundred
    values back, never the raster itself.

``synthetic``
    A physically-motivated simulation: a smooth brine/roughness field, an
    orographic wind-roughening gradient, a lead network generated by a distance
    transform, and seasonal fast-ice decay. It exists so the pipeline, the store
    and the dashboard are fully exercisable with no cloud credentials and no
    egress to Google. Every scene it produces is stamped
    ``provenance="synthetic"`` and the dashboard renders that as a visible badge.
    Synthetic data is never silently presented as observation.
"""

from __future__ import annotations

import hashlib
import logging
import math
import random
from collections.abc import Callable
from datetime import UTC, datetime, timedelta
from functools import partial
from typing import TYPE_CHECKING, Any, Final

from ..config import SAR_COLLECTIONS, SAR_RAW_ONLY
from ..errors import SourceError
from ..models import Colony, FastIceCell, SarScene, SourceHealth, utc_now
from ..net import HttpClient, retry_with_backoff

if TYPE_CHECKING:  # pragma: no cover - typing only
    from ..config import SarConfig

__all__ = [
    "SAR_BACKENDS",
    "BackscatterGrid",
    "SarClient",
    "classify_cell",
    "synthetic_scene",
]

_LOG = logging.getLogger("emperor.sources.sar")

SAR_BACKENDS: Final[tuple[str, ...]] = ("synthetic", "gee")

# Sigma0 bounds in dB for each surface class. Order matters: the classifier
# tests them from darkest to brightest.
_OPEN_WATER_MAX_DB: Final = -11.5
_NILAS_MAX_DB: Final = -8.5
_ICE_MAX_DB: Final = -2.5


def db(linear_power: float) -> float:
    """Convert a linear-power sigma0 sample to decibels.

    Earth Engine bands carry sigma0 as a linear ratio, and every threshold in
    this module is expressed in dB, so the conversion has to happen exactly
    once and in exactly one place. Doing it at the boundary is what keeps the
    stored series comparable: the fast-ice trend this project exists to detect
    is a small dB shift between acquisitions, and a missing or doubled 10*log10
    would turn that signal into noise without ever raising.

    Parameters
    ----------
    linear_power
        Sigma0 as a linear ratio, so 0.1 means -10 dB.

    Returns
    -------
    float
        The equivalent value in decibels.

    Raises
    ------
    ValueError
        If ``linear_power`` is not strictly positive, which for Earth Engine
        means a masked or out-of-footprint pixel rather than a measurement.

    Examples
    --------
    >>> round(db(0.1), 1)
    -10.0
    >>> round(db(1.0), 1)
    0.0
    >>> db(0.0)
    Traceback (most recent call last):
        ...
    ValueError: sigma0 must be strictly positive to convert to dB, got 0.0
    """
    if not linear_power > 0.0 or math.isinf(linear_power):
        msg = f"sigma0 must be strictly positive to convert to dB, got {linear_power}"
        raise ValueError(msg)
    return 10.0 * math.log10(linear_power)


def _incidence(value: Any) -> float | None:
    """Coerce a GEE incidence-angle property into a float or ``None``.

    Parameters
    ----------
    value
        The raw property, which may be missing, a string, or absent.

    Returns
    -------
    float | None
        The angle in degrees, or ``None`` when it is absent or unusable.
    """
    try:
        angle = float(value)
    except (TypeError, ValueError):
        return None
    return angle if 0.0 < angle < 90.0 else None


def _gee_provenance(band: str, raw_only: bool) -> str:
    """Build the provenance string identifying a GEE-derived scene.

    The string records both the collection and whether the band was calibrated,
    because a sigma0 series from the RAW product and one from GRD are not
    directly comparable and must not be pooled without that being visible.

    Parameters
    ----------
    band
        The polarisation that was reduced.
    raw_only
        Whether the band came from the uncalibrated RAW product.

    Returns
    -------
    str
        A provenance identifier.
    """
    dataset = SAR_COLLECTIONS.get(band, "COPERNICUS/S1_GRD")
    stage = "sigma0-uncalibrated" if raw_only else "sigma0"
    return f"gee.{dataset.split('/')[-1]}.{band}.{stage}"


def classify_cell(sigma0_db: float) -> tuple[str, bool]:
    """Classify a single sigma0 sample into a surface state.

    Parameters
    ----------
    sigma0_db
        Calibrated backscattering coefficient in dB.

    Returns
    -------
    tuple[str, bool]
        ``(classification, is_open_water)`` where classification is one of
        ``open_water``, ``nilas``, ``consolidated_ice`` or ``rough_ice``.

    Examples
    --------
    >>> classify_cell(-16.0)
    ('open_water', True)
    >>> classify_cell(-10.0)
    ('nilas', False)
    >>> classify_cell(-5.0)
    ('consolidated_ice', False)
    >>> classify_cell(-1.0)
    ('rough_ice', False)
    """
    if sigma0_db <= _OPEN_WATER_MAX_DB:
        return "open_water", True
    if sigma0_db <= _NILAS_MAX_DB:
        return "nilas", False
    if sigma0_db <= _ICE_MAX_DB:
        return "consolidated_ice", False
    return "rough_ice", False


class BackscatterGrid:
    """A square ``sigma0`` grid with the statistics derived from it.

    Parameters
    ----------
    cells
        Values in row-major order, ``size * size`` long.
    size
        Grid edge in cells.

    Examples
    --------
    >>> grid = BackscatterGrid([-6.0] * 9, 3)
    >>> grid.open_water_fraction
    0.0
    >>> round(grid.mean_db, 3)
    -6.0
    """

    __slots__ = ("cells", "max_db", "mean_db", "min_db", "open_water_fraction", "size", "std_db")

    def __init__(self, cells: list[float], size: int) -> None:
        """Initialise; see the class docstring for parameter semantics."""
        if size <= 0 or len(cells) != size * size:
            msg = f"grid needs exactly {size * size} cells for size {size}, got {len(cells)}"
            raise ValueError(msg)
        self.cells = cells
        self.size = size
        self.mean_db = sum(cells) / len(cells)
        self.min_db = min(cells)
        self.max_db = max(cells)
        variance = sum((c - self.mean_db) ** 2 for c in cells) / len(cells)
        self.std_db = math.sqrt(variance)
        self.open_water_fraction = sum(1 for c in cells if classify_cell(c)[1]) / len(cells)

    @property
    def frozen_ice_fraction(self) -> float:
        """Return the fraction of the grid that is not open water."""
        return 1.0 - self.open_water_fraction

    def as_matrix(self) -> list[list[float | None]]:
        """Return the grid as nested lists, with ``None`` for open water.

        Plotly renders ``None`` as a transparent gap, which is the honest
        depiction: there is no ice surface there to scatter from.

        Returns
        -------
        list[list[float | None]]
        """
        rows: list[list[float | None]] = []
        for index in range(self.size):
            row: list[float | None] = []
            for col in range(self.size):
                value = self.cells[index * self.size + col]
                row.append(None if classify_cell(value)[1] else value)
            rows.append(row)
        return rows


def _distance_transform_seeds(
    size: int,
    seeds: list[tuple[int, int, float]],
) -> list[float]:
    """Compute a multi-source distance field by two-pass chamfer relaxation.

    A cheap approximation of the Euclidean distance transform, used to grow
    leads outward from a set of seed points while keeping them thin and
    branching. O(size^2) with no dependencies, which matters for the
    zero-dependency daemon constraint.

    Parameters
    ----------
    size
        Grid edge in cells.
    seeds
        ``(row, col, weight)`` triples; weight scales the local radius.

    Returns
    -------
    list[float]
        Distance in cells from the nearest weighted seed.
    """
    infinity = 1e9
    distance = [infinity] * (size * size)
    for row, col, weight in seeds:
        if 0 <= row < size and 0 <= col < size:
            distance[row * size + col] = 0.0
            # A weighted seed is a *radius*, not a point: seed the disc.
            radius = max(0, round(weight))
            for dr in range(-radius, radius + 1):
                for dc in range(-radius, radius + 1):
                    rr, cc = row + dr, col + dc
                    if 0 <= rr < size and 0 <= cc < size:
                        offset = math.hypot(dr, dc) - weight
                        index = rr * size + cc
                        distance[index] = min(distance[index], offset)
    for row in range(size):
        for col in range(size):
            index = row * size + col
            best = distance[index]
            if row > 0:
                best = min(best, distance[index - size] + 1.0)
            if col > 0:
                best = min(best, distance[index - 1] + 1.0)
            if row > 0 and col > 0:
                best = min(best, distance[index - size - 1] + 1.4142)
            distance[index] = best
    for row in range(size - 1, -1, -1):
        for col in range(size - 1, -1, -1):
            index = row * size + col
            best = distance[index]
            if row < size - 1:
                best = min(best, distance[index + size] + 1.0)
            if col < size - 1:
                best = min(best, distance[index + 1] + 1.0)
            if row < size - 1 and col < size - 1:
                best = min(best, distance[index + size + 1] + 1.4142)
            distance[index] = best
    return distance


def _sentinel1_synthetic_grid(
    *,
    size: int,
    seed: int,
    day_of_year: int,
    breakup_phase: float,
    wind_index: float,
) -> list[float]:
    """Generate a physically-plausible ``sigma0`` field for one acquisition.

    The field is a sum of four terms, in the order a physical modeller would
    layer them:

    1. **Consolidated ice baseline** that brightens through the freezing season
       as brine drainage proceeds, then dims as the surface is wind-roughened.
    2. **Orographic wind roughening**, a large-scale gradient with a random
       orientation, because Antarctic katabatic flows are directional and their
       cross-track signature shows up strongly in sigma0.
    3. **Pressure ridges**, sparse bright linear features where floes raft.
    4. **Leads**, dark channels opened by a distance transform, whose density
       rises with the seasonal breakup phase.

    Parameters
    ----------
    size
        Grid edge in cells.
    seed
        RNG seed for reproducibility.
    day_of_year
        Drives the seasonal phase.
    breakup_phase
        0.0 = intact fast ice, 1.0 = fully dispersed.
    wind_index
        0.0 = calm, 1.0 = storm-force katabatic.

    Returns
    -------
    list[float]
        ``sigma0`` values in dB, row-major.
    """
    # synthetic scenes, seeded for reproducibility
    rng = random.Random(seed)
    centre = (size - 1) / 2.0

    # Wind-roughening orientation: random per acquisition, as real katabatic
    # flow directions are not stable between passes.
    wind_angle = rng.uniform(0.0, math.pi)
    cos_a, sin_a = math.cos(wind_angle), math.sin(wind_angle)

    # Brine drainage: sigma0 brightens over roughly Jun-Oct as brine is expelled
    # and the surface roughens on the centimetre scale.
    season = (day_of_year - 172) / 172.0  # 0 at solstice, 1 at the other solstice
    brine_brightening = 2.2 * max(0.0, min(1.0, season))

    # Leads: more numerous and more open as the season progresses.
    lead_density = 3 + int(breakup_phase * 22)
    seeds: list[tuple[int, int, float]] = []
    for _ in range(lead_density):
        row = rng.randrange(size)
        col = rng.randrange(size)
        radius = rng.uniform(0.0, 0.8 + breakup_phase * 1.9)
        seeds.append((row, col, radius))
    lead_distance = _distance_transform_seeds(size, seeds)

    cells: list[float] = []
    for row in range(size):
        for col in range(size):
            index = row * size + col

            # 1. Baseline consolidated ice.
            sigma = -8.4 + brine_brightening

            # 2. Orographic wind roughening: a smooth directional gradient that
            #    brightens the upwind side of ridges. Cross-track wind is the
            #    dominant control on C-band sea-ice sigma0 in the literature.
            r = (row - centre) / centre if centre else 0.0
            c = (col - centre) / centre if centre else 0.0
            projection = r * cos_a + c * sin_a
            sigma += 2.6 * wind_index * projection

            # 3. Pressure ridges: sparse bright speckle from rafted floes.
            if rng.random() < 0.004 + 0.010 * wind_index:
                sigma += rng.uniform(1.5, 4.2)

            # 4. Leads: dark channels. The chamfer distance gives a smooth falloff
            #    so leads have edges (nilas margins) rather than hard steps.
            lead = max(0.0, lead_distance[index])
            if lead < 3.0:
                lead_strength = (1.0 - lead / 3.0) * (0.55 + 0.45 * breakup_phase)
                sigma -= 9.5 * lead_strength
                if lead > 1.2:
                    # Nilas transition zone: slightly dark, not open water.
                    sigma += 2.0

            # Local roughness speckle so the field is not visibly synthetic at
            # the cell level.
            sigma += rng.gauss(0.0, 0.55 + 0.5 * wind_index)

            cells.append(max(-22.0, min(-0.5, sigma)))

    return cells


def seasonal_breakup_phase(day_of_year: int) -> float:
    """Return the fast-ice breakup phase for a day of the austral year.

    The model is deliberately **asymmetric**, because sea ice is. A cosine
    would imply a smooth six-month melt; the observed cycle is a long
    consolidation season with a short, abrupt melt:

    ==========================  ==================
    Period (austral)            Breakup phase
    ==========================  ==================
    day 100-320 (Mar-Oct)       0.00-0.06 consolidated
    day 320-380 (Nov-Dec)       0.06-0.85 accelerating
    day 380-400 (Dec-Jan)       0.85-1.00 near-total
    day 40-100 (Feb-Mar)        1.00-0.20 ablating
    ==========================  ==================

    For a Ross Sea fast-ice colony the practical consequence is stark and is
    exactly the exposure this project exists to watch: a colony that must
    sustain a ~10-month breeding cycle on fast ice has its entire reproductive
    success concentrated in the handful of weeks when this function returns a
    high value.

    Parameters
    ----------
    day_of_year
        Day number 1-365.

    Returns
    -------
    float
        0.0 for intact consolidated fast ice, 1.0 for fully dispersed.

    Examples
    --------
    >>> round(seasonal_breakup_phase(200), 2)   # midwinter, consolidated
    0.04
    >>> seasonal_breakup_phase(15)              # midsummer, dispersed
    1.0
    >>> round(seasonal_breakup_phase(350), 2)   # spring breakup under way
    0.46
    """
    day = day_of_year % 365
    if 100 <= day <= 320:
        # Slow, weak reconsolidation through the winter.
        return 0.02 + 0.04 * (day - 100) / 220.0
    if 320 < day <= 380:
        return 0.06 + 0.79 * (day - 320) / 60.0
    if 380 < day < 400:
        return 0.85 + 0.15 * (day - 380) / 20.0
    if day >= 40:
        # Melt season: fast ice ablates through Feb and re-freezes through Mar.
        return 1.0 - 0.80 * (day - 40) / 60.0
    # Wrapped: early January.
    return 1.0


def synthetic_scene(
    *,
    colony: Colony,
    scene_index: int,
    observed_at: datetime,
    cells: int,
    seed: int = 0,
    platform: str = "SENTINEL-1",
    orbit_type: str = "ASCENDING",
    polarisation: str = "HH",
    incidence_angle_deg: float = 33.0,
    backscatter_trend: float = 0.0,
) -> SarScene:
    """Build one simulated Sentinel-1 acquisition over a colony.

    Parameters
    ----------
    colony
        The colony being imaged.
    scene_index
        Ordinal of the acquisition; drives the seasonal and breakup phase so a
        run of scenes forms a coherent, physically ordered history.
    observed_at
        Acquisition time.
    cells
        Grid edge in cells.
    seed
        Base seed. Combined with ``colony_id`` and ``scene_index`` so a node
        always regenerates an identical history for the same configuration.
    platform, orbit_type, polarisation
        Recorded on the scene as if retrieved.
    incidence_angle_deg
        Recorded incidence angle.
    backscatter_trend
        Extra dB applied to every cell per scene index. Lets a test or a demo
        inject a fast-ice deterioration trend without changing the physical
        model.

    Returns
    -------
    SarScene
        The scene, stamped ``provenance="synthetic.sar-simulator/v1"``.

    Examples
    --------
    >>> from emperor_space_tracker.models import BreedingHabitat, Colony
    >>> colony = Colony(
    ...     "test", "Test", -77.5, 166.6, "test", 1000, 2023, "test",
    ...     "Aptenodytes forsteri", BreedingHabitat.FAST_ICE, 0.9,
    ... )
    >>> scene = synthetic_scene(colony=colony, scene_index=0,
    ...                        observed_at=utc_now(), cells=9, seed=7)
    >>> scene.is_synthetic
    True
    >>> len(scene.cells)
    81
    """
    digest = hashlib.sha256(
        f"{seed}:{colony.colony_id}".encode()
    ).digest()
    scene_seed = int.from_bytes(digest[:8], "big") + scene_index * 7919

    day_of_year = observed_at.timetuple().tm_yday
    # Breakup is driven by the *acquisition date*, not by scene_index, so a
    # backfill series shows the real seasonal arc rather than an arbitrary one.
    # A small per-scene term keeps two acquisitions on the same day from being
    # byte-identical, as two real passes never are.
    breakup = max(0.0, min(1.0, seasonal_breakup_phase(day_of_year) + 0.02 * scene_index))
    # Katabatic wind speed varies between passes and is the dominant control on
    # C-band sigma0, so it is decorrelated from the date.
    wind_index = 0.28 + 0.42 * ((scene_index * 37) % 7) / 6.0

    values = _sentinel1_synthetic_grid(
        size=cells,
        seed=scene_seed,
        day_of_year=day_of_year,
        breakup_phase=breakup,
        wind_index=wind_index,
    )
    if backscatter_trend:
        values = [max(-22.0, v + backscatter_trend * scene_index) for v in values]

    grid = BackscatterGrid(values, cells)
    scene_id = (
        f"SYNTHETIC-{colony.colony_id.upper()}-{observed_at.strftime('%Y%m%dT%H%M%SZ')}"
    )

    return SarScene(
        scene_id=scene_id,
        observed_at=observed_at,
        platform=platform,
        orbit_type=orbit_type,
        polarisation=polarisation,
        incidence_angle_deg=incidence_angle_deg,
        colony_id=colony.colony_id,
        mean_db=grid.mean_db,
        min_db=grid.min_db,
        max_db=grid.max_db,
        std_db=grid.std_db,
        frozen_ice_fraction=grid.frozen_ice_fraction,
        open_water_fraction=grid.open_water_fraction,
        cells=tuple(
            FastIceCell(
                scene_id=scene_id,
                row=row,
                col=col,
                sigma0_db=value,
                is_open_water=classify_cell(value)[1],
                classification=classify_cell(value)[0],
            )
            for row in range(cells)
            for col, value in enumerate(values[row * cells : (row + 1) * cells])
        ),
        provenance="synthetic.sar-simulator/v1",
        bytes_processed=cells * cells * 4,
    )


class SarClient:
    """Fetches fast-ice backscatter for a colony, via GEE or the simulator.

    Parameters
    ----------
    client
        Shared HTTP client, used for reachability probes and the GEE asset
        metadata lookups.
    config
        The ``[sar]`` configuration section.

    Examples
    --------
    >>> from emperor_space_tracker.config import load_config
    >>> from emperor_space_tracker.net import HttpClient
    >>> cfg = load_config(use_user_config=False)
    >>> sar = SarClient(HttpClient(), cfg.sar)  # doctest: +SKIP
    """

    def __init__(self, client: HttpClient, config: SarConfig) -> None:
        """Initialise; see the class docstring for parameter semantics."""
        self.client = client
        self.config = config

    @property
    def backend(self) -> str:
        """Return the configured backend name.

        Returns
        -------
        str
            ``"synthetic"`` or ``"gee"``.
        """
        return self.config.backend

    def is_available(self) -> tuple[bool, str]:
        """Report whether the configured backend can actually run.

        Returns
        -------
        tuple[bool, str]
            ``(available, reason)``. Never raises. This is what lets the daemon
            fall back rather than crash when GEE credentials are absent on a
            node that was provisioned without them.
        """
        if self.config.backend == "synthetic":
            return True, "built-in backscatter simulator, no credentials required"
        try:
            import earthengine
        except ImportError:
            return False, (
                "sar.backend='gee' but earthengine-api is not installed; "
                "run `uv sync --extra sar` or switch to backend='synthetic'"
            )
        try:
            import ee

            ee.Initialize()
        except Exception as exc:
            return False, (
                f"Google Earth Engine is installed but not authenticated: {exc}. "
                "Run `earthengine authenticate`."
            )
        return True, "Google Earth Engine authenticated"

    def _ages(
        self,
        colonies: list[Colony],
        observed: datetime,
        latest_acquisition: dict[str, datetime] | None,
    ) -> list[tuple[Colony, float]]:
        """Pair each colony with the hours since its last stored frame.

        Colonies with no stored frame are omitted rather than reported as age
        zero: they are not holding, they are simply unknown, and rounding them
        to 0 h in an operator-facing message would read as "just acquired".
        """
        pairs: list[tuple[Colony, float]] = []
        for colony in colonies:
            last = (latest_acquisition or {}).get(colony.colony_id)
            if last is None:
                continue
            pairs.append((colony, (observed - last).total_seconds() / 3600.0))
        return pairs

    def poll(
        self,
        *,
        colonies: list[Colony],
        scenes_per_colony: int = 1,
        now: datetime | None = None,
        latest_acquisition: dict[str, datetime] | None = None,
    ) -> tuple[list[SarScene], list[SourceHealth]]:
        """Fetch backscatter scenes for the fast-ice-breeding colonies given.

        Colonies whose :attr:`~emperor_space_tracker.models.Colony.breeding_habitat`
        is not ``FAST_ICE`` are skipped, and reported as skipped. They are not
        an error: a land-nesting species has no fast ice under it, so sigma0
        from a footprint around its colony describes the water and shore
        nearby, and every classification band and trend threshold downstream is
        calibrated for consolidated sea ice. Imaging one anyway would put a
        confident-looking number in the store that measures nothing about the
        birds -- which is the failure mode this whole project is built to avoid.

        Parameters
        ----------
        colonies
            Colonies to image. Empty list is valid and yields no scenes.
        scenes_per_colony
            How many acquisitions to produce per colony per pass.
        now
            Override for the acquisition timestamp, so a backfill run can be
            given a deterministic clock.
        latest_acquisition
            Newest stored acquisition per ``colony_id``. A colony whose last
            frame is younger than :attr:`~emperor_space_tracker.config.SarConfig.revisit_hours`
            is left alone and reported as not due. This is the radar's revisit
            interval, and it is independent of the daemon's poll interval: the
            poll loop runs five-minuteutely because space weather moves that
            fast, and generating a fresh 41x41 grid on every pass would invent
            144 daily observations from a sensor that flies twice.

        Returns
        -------
        tuple[list[SarScene], list[SourceHealth]]
            Scenes and per-source health. With the GEE backend unavailable, the
            synthetic backend is used as a fallback and the health entry says so
            in plain language, because a silent backend swap is exactly the kind
            of thing that invalidates an operator's trust in a monitoring node.
        """
        if not colonies:
            return [], [
                SourceHealth("sar", True, 0, "no colonies in range; nothing to image", 0)
            ]

        imaged = [c for c in colonies if c.monitors_fast_ice]
        skipped = [c for c in colonies if not c.monitors_fast_ice]
        if skipped:
            _LOG.info(
                "skipping %d of %d colony(ies) for SAR: %s",
                len(skipped),
                len(colonies),
                ", ".join(f"{c.name} ({c.breeding_habitat})" for c in skipped),
            )
        if not imaged:
            return [], [
                SourceHealth(
                    "sar",
                    True,
                    0,
                    f"no fast-ice-breeding colonies among {len(colonies)}; "
                    "fast-ice backscatter does not apply to this species",
                    0,
                )
            ]

        available, reason = self.is_available()
        backend = self.config.backend if available else "synthetic"
        if not available:
            _LOG.warning(
                "configured SAR backend %r unavailable (%s); using the synthetic "
                "backend for this pass. Scenes will be labelled synthetic.",
                self.config.backend,
                reason,
            )

        observed = now or utc_now()
        health: list[SourceHealth] = []
        scenes: list[SarScene] = []
        started = utc_now()

        # Split the in-range colonies by whether the radar is actually due over
        # them yet. This is a sensor property, not a storage optimisation, so it
        # applies to the GEE backend as well: asking Earth Engine for a frame
        # that has not been acquired yet returns nothing.
        due: list[Colony] = []
        waiting: list[Colony] = []
        window = timedelta(hours=self.config.revisit_hours)
        for colony in imaged:
            last = (latest_acquisition or {}).get(colony.colony_id)
            if last is not None and observed - last < window:
                waiting.append(colony)
            else:
                due.append(colony)

        if not due:
            ages = ", ".join(
                f"{colony.colony_id} {age:.1f}h"
                for colony, age in self._ages(waiting, observed, latest_acquisition)
            )
            return [], [
                SourceHealth(
                    "sar",
                    True,
                    0,
                    f"revisit window {self.config.revisit_hours:g}h not elapsed; "
                    f"holding {len(waiting)} colony(ies): {ages}",
                    0,
                    observed,
                )
            ]

        if backend == "gee":
            for colony in due:
                fetched, detail = self._poll_gee(colony, scenes_per_colony, observed)
                scenes.extend(fetched)
                health.append(
                    SourceHealth("sar", bool(fetched), 0, detail, len(fetched), observed)
                )
        else:
            # Spread the backfill series across the lookback window so the
            # seasonal breakup model actually produces an arc. Requesting 12
            # scenes over 30 days steps 2.7 days at a time and walks the whole
            # consolidation-to-breakup transition; stacking them all on today's
            # date would produce 12 near-identical frames and a flat line that
            # tells the operator nothing.
            count = max(1, scenes_per_colony)
            step_days = max(1.0, self.config.lookback_days / count)
            for colony in due:
                for index in reversed(range(count)):
                    acquisition = observed - timedelta(days=index * step_days)
                    scenes.append(
                        synthetic_scene(
                            colony=colony,
                            scene_index=index,
                            observed_at=acquisition,
                            cells=self.config.grid_cells,
                            seed=self.config.synthetic_seed,
                            platform=self.config.platform,
                            orbit_type=self.config.orbit_type,
                            polarisation=self.config.polarisation,
                        )
                    )
            detail = (
                f"{len(scenes)} synthetic scene(s) across {len(due)} colony(ies), "
                f"{step_days:.1f} day spacing, "
                f"{self.config.grid_cells}x{self.config.grid_cells} cells"
            )
            if skipped:
                detail += f"; {len(skipped)} non-fast-ice colony(ies) skipped"
            if waiting:
                aged = self._ages(waiting, observed, latest_acquisition)
                held = ", ".join(f"{c.colony_id} {age:.1f}h" for c, age in aged)
                detail += (
                    f"; {len(waiting)} held inside the "
                    f"{self.config.revisit_hours:g}h revisit window: {held}"
                )
            if not available:
                detail = f"fallback: {reason}. {detail}"
            health.append(SourceHealth("sar", True, 0, detail, len(scenes), observed))

        elapsed = int((utc_now() - started).total_seconds() * 1000)
        if health:
            health[0] = SourceHealth(
                "sar", health[0].ok, elapsed, health[0].detail, health[0].record_count, observed
            )
        return scenes, health

    # -- Google Earth Engine backend ---------------------------------------

    def _collection(self, colony: Colony) -> Any:
        """Build the filtered Sentinel-1 collection covering one colony.

        The collection is chosen from the configured polarisation rather than
        hardcoded, because the products are not interchangeable: GRD carries
        only VV and VH, so asking it for HH yields an empty selection rather
        than an error. See :data:`~emperor_space_tracker.config.SAR_COLLECTIONS`.

        Parameters
        ----------
        colony
            Colony whose footprint bounds the query.

        Returns
        -------
        Any
            An ``ee.ImageCollection``.

        Raises
        ------
        SourceError
            If Earth Engine is not installed or cannot be initialised.
        """
        try:
            import ee
        except ImportError as exc:
            msg = f"earthengine-api is not installed: {exc}"
            raise SourceError("sar.gee", msg) from exc
        try:
            ee.Initialize()
        except Exception as exc:
            msg = f"Earth Engine initialisation failed: {exc}"
            raise SourceError("sar.gee", msg) from exc

        band = self.config.polarisation.upper()
        dataset = SAR_COLLECTIONS.get(band, "COPERNICUS/S1_GRD")
        start = utc_now() - timedelta(days=self.config.lookback_days)
        return (
            ee.ImageCollection(dataset)
            .filterBounds(ee.Geometry.Point([colony.longitude, colony.latitude]))
            .filterDate(ee.Date(start), ee.Date(utc_now()))
            .filter(ee.Filter.eq("platform_number", self.config.platform))
            .filter(ee.Filter.eq("orbitProperties_pass", self.config.orbit_type))
        )

    def _poll_gee(
        self,
        colony: Colony,
        limit: int,
        observed: datetime,
    ) -> tuple[list[SarScene], str]:
        """Retrieve genuine Sentinel-1 backscatter for one colony.

        The reduction runs entirely in Earth Engine: ``reduceRegion`` with
        ``crs="EPSG:327X"`` (a polar stereographic CRS) aggregates the GRD scene
        to a fixed grid over the colony buffer. Only the resulting value matrix
        crosses the network, which is what keeps this usable from a small node.

        Parameters
        ----------
        colony
            Colony to image.
        limit
            Maximum scenes.
        observed
            Timestamp for health records.

        Returns
        -------
        tuple[list[SarScene], str]
            ``(scenes, detail)``. An empty list with an explanatory detail string
            when no acquisition covers the colony in the lookback window -- a
            normal outcome, not an error.
        """
        try:
            import ee
        except ImportError:
            return [], "earthengine-api became unavailable mid-poll"

        try:
            collection = self._collection(colony)
            count = int(collection.size().getInfo())
        except SourceError as exc:
            return [], str(exc)
        except Exception as exc:
            return [], f"collection query failed: {exc}"

        if count == 0:
            return [], (
                f"no {self.config.platform} {self.config.orbit_type} acquisition covers "
                f"{colony.name} in the last {self.config.lookback_days} days"
            )

        grid = self.config.grid_cells
        extent = self._grid_geometry(colony)
        band = self.config.polarisation.upper()
        raw_only = band in SAR_RAW_ONLY

        def _reduce(index: int, _colony: str = colony.colony_id) -> SarScene | None:
            """Reduce the n-th scene in the collection to a backscatter matrix."""
            image = ee.Image(collection.toList(count).get(index))
            # Read only the requested band. Selecting a band the collection does
            # not carry raises deep inside Earth Engine with an opaque message,
            # so the band is validated against the dataset in _collection.
            stats = image.select(band).reduceRegion(
                **{
                    "reducer": ee.Reducer.toList(grid * grid),
                    "geometry": extent,
                    "crs": self._polar_crs(colony.latitude),
                    "scale": self.config.resolution_meters,
                    "maxPixels": 1e7,
                    "tileScale": 4,
                }
            )
            values = stats.get(band)
            if values is None or len(values.getInfo() or []) == 0:
                return None
            return self._scene_from_reduction(
                image=image,
                values=[float(v) for v in values.getInfo()],
                colony=colony,
                grid=grid,
                index=index,
                band=band,
                raw_only=raw_only,
            )

        scenes: list[SarScene] = []
        for index in range(min(count, max(1, limit))):
            reduce_one: Callable[[], SarScene | None] = partial(_reduce, index)
            try:
                scene = retry_with_backoff(reduce_one, attempts=2)
            except Exception as exc:
                _LOG.warning("scene %d for %s failed: %s", index, colony.name, exc)
                continue
            if scene is not None:
                scenes.append(scene)

        detail = f"{len(scenes)} of {count} Sentinel-1 acquisition(s) reduced over {colony.name}"
        return scenes, detail

    def _grid_geometry(self, colony: Colony) -> Any:
        """Return the square analysis footprint centred on a colony.

        The footprint is sized from the configured ``radius_meters``. The
        ``reduceRegion`` call samples a ``grid_cells`` by ``grid_cells`` matrix at
        ``resolution_meters`` posting, so exact coverage needs
        ``2 * radius_meters == grid_cells * resolution_meters``; a mismatch is
        logged so the operator can see the sampling drift instead of
        discovering it as a silent corner-crop (the reducer truncates to the
        first ``grid²`` values) or NaN padding.

        Parameters
        ----------
        colony
            Colony to centre on.

        Returns
        -------
        Any
            An ``ee.Geometry.Rectangle`` in degrees, sized to the configured
            radius.
        """
        import ee

        half_km = self.config.radius_meters / 1000.0
        sampled_m = self.config.grid_cells * self.config.resolution_meters
        if abs(2 * self.config.radius_meters - sampled_m) / max(1, sampled_m) > 0.10:
            _LOG.debug(
                "SAR footprint radius %dm diverges from sampling grid %dx%dm; "
                "keep 2*radius_meters == grid_cells*resolution_meters for exact coverage",
                self.config.radius_meters,
                self.config.grid_cells,
                self.config.resolution_meters,
            )
        # 1 degree latitude is a constant 111.32 km anywhere on the globe.
        d_lat = half_km / 111.32
        # Longitude degrees converge toward the pole; correct for the cos(lat).
        cos_lat = max(0.05, abs(math.cos(math.radians(colony.latitude))))
        d_lon = d_lat / cos_lat
        return ee.Geometry.Rectangle(
            [colony.longitude - d_lon, colony.latitude - d_lat],
            [colony.longitude + d_lon, colony.latitude + d_lat],
            proj="EPSG:4326",
            geodesic=False,
        )

    @staticmethod
    def _polar_crs(latitude: float) -> str:
        """Return the EPSG code of the polar stereographic CRS covering ``latitude``.

        This node monitors Antarctic colonies only, so the southern UPS zone
        (EPSG:3271, 60S-90S) is the one correct answer. A latitude north of
        -60 raises rather than returning the Arctic zone: reprojecting into
        the wrong hemisphere produces a plausible-looking but geometrically
        wrong grid, and failing loudly beats silently corrupting sigma0.

        Parameters
        ----------
        latitude
            Colony latitude in degrees.

        Returns
        -------
        str
            An EPSG code string.
        """
        if latitude >= -60:
            msg = f"colony latitude {latitude} is outside the Antarctic domain (< -60)"
            raise ValueError(msg)
        return "EPSG:3271"

    def _scene_from_reduction(
        self,
        *,
        image: Any,
        values: list[float],
        colony: Colony,
        grid: int,
        index: int,
        band: str,
        raw_only: bool,
    ) -> SarScene:
        """Build a :class:`~emperor_space_tracker.models.SarScene` from GEE values.

        The values arriving here are sigma0 in *linear power*, which is what the
        GEE band carries for both products: the GRD product is pre-calibrated to
        sigma0 by the Copernicus pipeline, and the RAW product is calibrated in
        the reduction that produced these samples. :func:`db` then converts to
        decibels. Both matter, because the fast-ice trend signal this project
        detects is a small dB change between acquisitions, and reading linear
        power as dB -- or vice versa -- silently destroys the only signal that
        matters.

        Parameters
        ----------
        image
            The ``ee.Image`` being reduced, used for scene metadata.
        values
            Linear-power backscatter samples, already sigma0-calibrated.
        colony
            Colony imaged.
        grid
            Grid edge in cells.
        index
            Ordinal in the collection.
        band
            Polarisation actually reduced, e.g. ``"VV"``.
        raw_only
            Whether ``band`` came from the uncalibrated RAW product.

        Returns
        -------
        SarScene
        """
        grid_values = values[: grid * grid]
        if len(grid_values) < grid * grid:
            grid_values.extend([float("nan")] * (grid * grid - len(grid_values)))

        # The reducer returns linear-power sigma0. Anything at or below zero is
        # outside the footprint or a masked fill, and db() would raise on it, so
        # it is folded to the open-water floor. This is a deliberately lossy
        # choice: the alternative is discarding the whole scene because a few
        # cells at the edge of a colony's square lack valid pixels.
        cleaned = [db(v) if v > 0 else -22.0 for v in grid_values]

        stats = BackscatterGrid(cleaned, grid)

        # Scene *properties* live on the image, not on its bands. Reading them off
        # a selected band returns band metadata (gain, projection, checksum),
        # which has none of the keys looked up below and silently yields the
        # fallback values and a "now" timestamp for every scene.
        try:
            info = dict(image.getInfo() or {})
        except Exception:
            info = {}

        scene_id = str(
            info.get("system:index")
            or info.get("id")
            or f"S1-{colony.colony_id.upper()}-{index:03d}"
        )
        observed_at = observed_from_scene(info) or utc_now()
        incidence = _incidence(info.get("incidenceAngle"))

        return SarScene(
            scene_id=scene_id,
            observed_at=observed_at,
            platform=str(info.get("platform_number") or self.config.platform),
            orbit_type=str(info.get("orbitProperties_pass") or self.config.orbit_type),
            polarisation=band,
            incidence_angle_deg=incidence,
            colony_id=colony.colony_id,
            mean_db=stats.mean_db,
            min_db=stats.min_db,
            max_db=stats.max_db,
            std_db=stats.std_db,
            frozen_ice_fraction=stats.frozen_ice_fraction,
            open_water_fraction=stats.open_water_fraction,
            cells=tuple(
                FastIceCell(
                    scene_id=scene_id,
                    row=row,
                    col=col,
                    sigma0_db=value,
                    is_open_water=classify_cell(value)[1],
                    classification=classify_cell(value)[0],
                )
                for row in range(grid)
                for col, value in enumerate(cleaned[row * grid : (row + 1) * grid])
            ),
            provenance=_gee_provenance(band, raw_only),
            bytes_processed=len(cleaned) * 8,
        )


def observed_from_scene(info: dict[str, Any]) -> datetime | None:
    """Extract an acquisition time from a GEE scene's metadata.

    Parameters
    ----------
    info
        The scene property dictionary.

    Returns
    -------
    datetime | None
        Aware UTC datetime, or ``None`` if no usable start time is present.
    """
    raw = info.get("system:time_start")
    if raw is None:
        return None
    try:
        return datetime.fromtimestamp(int(raw) / 1000.0, tz=UTC)
    except (TypeError, ValueError, OSError, OverflowError):
        return None
